### ISSUE TITLE
运行npm run build时，提示“Cannot find module '/home/li/Documents/gxcc/build/webpack.config.js'”

### ISSUE THREAD

**Issue by baidang201** [gxchain/gxx-server#6]
**Describe the bug**
在ubuntu16.04下编译gxcc代码（npm run build），报错 “Error: Cannot find module '/home/li/Documents/gxcc/build/webpack.config.js'
”

**To Reproduce**
1. 安装nvm, 
npm install nvm 
nvm install 6
nvm alias default 6
nvm use 6

2. 下载代码，安装依赖库
git clone git@github.com:gxchain/gxcc.git
cd gxcc
npm install

3. 运行gxcc
npm start
```
> gxcc@1.0.0 start /home/li/Documents/gxcc
> nodemon lib/index.js --exec babel-node --watch lib

[nodemon] 1.18.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/li/Documents/gxcc/lib/**/*
[nodemon] starting `babel-node lib/index.js`
Example app listening on port 3000
```

4. 执行npm run build， See error
```
li@ubuntu:~/Documents/gxcc$ npm run build

> gxcc@1.0.0 prebuild /home/li/Documents/gxcc
> npm run clean


> gxcc@1.0.0 clean /home/li/Documents/gxcc
> rm -rf ./dist/*


> gxcc@1.0.0 build /home/li/Documents/gxcc
> webpack --progress --hide-modules --config build/webpack.config.js

module.js:478
    throw err;
    ^

Error: Cannot find module '/home/li/Documents/gxcc/build/webpack.config.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/li/Documents/gxcc/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/li/Documents/gxcc/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (/home/li/Documents/gxcc/node_modules/webpack/bin/convert-argv.js:107:15)
    at Object.<anonymous> (/home/li/Documents/gxcc/node_modules/webpack/bin/webpack.js:153:40)
    at Module._compile (module.js:577:32)

npm ERR! Linux 4.4.0-130-generic
npm ERR! argv "/home/li/.nvm/versions/node/v6.14.4/bin/node" "/home/li/.nvm/versions/node/v6.14.4/bin/npm" "run" "build"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! gxcc@1.0.0 build: `webpack --progress --hide-modules --config build/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gxcc@1.0.0 build script 'webpack --progress --hide-modules --config build/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gxcc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --hide-modules --config build/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gxcc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gxcc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/li/Documents/gxcc/npm-debug.log
li@ubuntu:~/Documents/gxcc$ node -v
v6.14.4
```

**Expected behavior**
期望能编译项目成功

**Screenshots**
![image](https://user-images.githubusercontent.com/3405789/44325662-03260480-a48c-11e8-91ef-0b43fc2a812b.png)

**Desktop (please complete the following information):**
 - OS:    Ubuntu 64位
 - Version 16.04

**Comment by lanhaoxiang** [comment]
已修复, 感谢反馈
可在下方提供gxchain账号

**Comment by baidang201** [comment]
bai201

**Comment by lanhaoxiang** [comment]
已发出，请查收
